env:
    browser: true
    es6: true
extends: google
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
parserOptions:
    ecmaVersion: 2018
# plugins:
#    - vue
rules:
    curly: ["off"]
    indent: ["error", 4, { "outerIIFEBody": 0 }]
    max-len: ["error", 100]
    no-var: ["off"]
    quotes: ["off"]
    require-jsdoc: ["off"]


