# Base URL for web site
base_url: /
# Location of the database
tunes_db: /srv/tunes-data/tunes.sqlite
# Site auth secret; see make_secret script.
# CHANGE THIS
site_secret: QUFBQUFBQUFBQUFBQUFBQQ
# The admin (and only user)
admin_username: john.doe
# Password for the admin user; see crypt_password script. Below is "password1".
# CHANGE THIS
admin_password: 16384$8$1$Fil32HZVnzuBRqBp4FMkRA$7Y2ZV1NNO2PiSc8abnWASn5AgtjRKTIivWgnb6zg06A