#!/usr/bin/python2

import password_utils
import termios
import sys

# From the termios docs
def getpass(prompt = "Password: "):
    fd = sys.stdin.fileno()
    old = termios.tcgetattr(fd)
    new = termios.tcgetattr(fd)
    new[3] = new[3] & ~termios.ECHO          # lflags
    try:
        termios.tcsetattr(fd, termios.TCSADRAIN, new)
        passwd = raw_input(prompt)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old)
    return passwd

pw = getpass("New password: ")
print
pw2 = getpass("Repeat: ")
print

if pw != pw2:
    print >>sys.stderr, ("Passwords don't match")
    sys.exit(1)

print password_utils.crypt_password(pw)

