#!/usr/bin/python2

import os
import pwd
import sys

import config
import password_utils

web_uid = pwd.getpwnam(config.WEB_USER).pw_uid
web_gid = pwd.getpwnam(config.WEB_GROUP).pw_uid

if os.path.exists(config.SITE_SECRET):
    print "%s already exists. Replace? [Ny] " % (config.SITE_SECRET,),
    l = sys.stdin.readline()
    if len(l) == 0 or (l[0] != 'y' and l[0] != 'Y'):
        sys.exit(0)

    print "Saving as", config.SITE_SECRET + ".bak"
    os.rename(config.SITE_SECRET, config.SITE_SECRET + ".bak")

fd = os.open(config.SITE_SECRET, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0700)
f = os.fdopen(fd, "w")
print >>f, password_utils.encode_128(password_utils.random_bytes(16))
f.close()

try:
    os.chown(config.SITE_SECRET, web_uid, web_gid)
except OSError:
    print >>sys.stderr, "Can't change permissions on site secret file. Maybe you need to run this as root?"
    sys.exit(1)

